<?php
/**
 * MRRlytics API Endpoint
 * 
 * Entry point for data extraction requests.
 * Handles authentication, rate limiting, and JSON responses.
 * 
 * @package    MRRlytics
 * @author     MRRlytics Team
 * @version    1.0.0
 * @license    MIT
 * 
 * @requires   PHP 7.2+
 * @requires   WHMCS 8.0+
 */

// Start output buffering FIRST to capture any unexpected output
ob_start();

// Debug mode - enable BEFORE anything else
$debugMode = isset($_GET['debug']) && $_GET['debug'] === '1';

if ($debugMode) {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
    ini_set('log_errors', '1');
    
    // Custom error handler to output JSON
    set_error_handler(function($errno, $errstr, $errfile, $errline) {
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'error' => [
                'code' => $errno,
                'message' => $errstr,
                'file' => $errfile,
                'line' => $errline,
            ]
        ], JSON_PRETTY_PRINT);
        exit;
    });
    
    // Custom exception handler
    set_exception_handler(function($e) {
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'error' => [
                'code' => $e->getCode(),
                'message' => $e->getMessage(),
                'file' => $e->getFile(),
                'line' => $e->getLine(),
            ]
        ], JSON_PRETTY_PRINT);
        exit;
    });
    
    // Catch fatal errors
    register_shutdown_function(function() {
        $error = error_get_last();
        if ($error && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
            header('Content-Type: application/json; charset=utf-8');
            echo json_encode([
                'success' => false,
                'error' => [
                    'code' => $error['type'],
                    'message' => $error['message'],
                    'file' => $error['file'],
                    'line' => $error['line'],
                    'type' => 'fatal'
                ]
            ], JSON_PRETTY_PRINT);
        }
    });
}

// Prevent direct access without WHMCS context
if (!defined('WHMCS')) {
    // Attempt to load the WHMCS framework
    $whmcsInitPath = __DIR__ . '/../../../init.php';
    
    if (!file_exists($whmcsInitPath)) {
        ob_end_clean();
        http_response_code(500);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'error'   => [
                'code'    => 500,
                'message' => 'WHMCS framework not found',
            ],
        ], JSON_PRETTY_PRINT);
        exit;
    }
    
    // Suppress any output from WHMCS init
    try {
        require_once $whmcsInitPath;
    } catch (\Exception $e) {
        ob_end_clean();
        http_response_code(500);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'success' => false,
            'error'   => [
                'code'    => 500,
                'message' => 'WHMCS init failed: ' . $e->getMessage(),
            ],
        ], JSON_PRETTY_PRINT);
        exit;
    }
    
    // Clear any output generated by WHMCS init
    ob_clean();
}

use Illuminate\Database\Capsule\Manager as Capsule;

// Verify WHMCS loaded correctly
if (!class_exists('Illuminate\Database\Capsule\Manager')) {
    ob_end_clean();
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode([
        'success' => false,
        'error'   => [
            'code'    => 500,
            'message' => 'Database capsule not available. WHMCS may not be properly initialized.',
        ],
    ], JSON_PRETTY_PRINT);
    exit;
}

// Execution configuration
set_time_limit(0);
ini_set('memory_limit', '512M');

// Response headers
header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');

/**
 * Send a JSON response and terminate execution
 * 
 * @param array $data     Data to send
 * @param int   $httpCode HTTP status code
 * 
 * @return void
 */
function sendJsonResponse($data, $httpCode = 200)
{
    // Clear any buffered output
    while (ob_get_level() > 0) {
        ob_end_clean();
    }
    
    http_response_code($httpCode);
    header('Content-Type: application/json; charset=utf-8');
    
    // Sanitize data to ensure valid JSON output
    $data = sanitizeForJson($data);
    
    $jsonFlags = JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES;
    
    // PHP 7.2+ supports JSON_INVALID_UTF8_SUBSTITUTE
    if (defined('JSON_INVALID_UTF8_SUBSTITUTE')) {
        $jsonFlags |= JSON_INVALID_UTF8_SUBSTITUTE;
    }
    
    echo json_encode($data, $jsonFlags);
    exit;
}

/**
 * Recursively sanitize data for JSON encoding
 * Removes invalid UTF-8 characters and control characters
 * 
 * @param mixed $data Data to sanitize
 * @return mixed Sanitized data
 */
function sanitizeForJson($data)
{
    if (is_array($data)) {
        // Re-index numeric arrays to avoid sparse arrays with null gaps
        $isNumeric = array_keys($data) === range(0, count($data) - 1);
        $result = [];
        foreach ($data as $key => $value) {
            $sanitizedValue = sanitizeForJson($value);
            if ($sanitizedValue !== null || !$isNumeric) {
                if ($isNumeric) {
                    $result[] = $sanitizedValue;
                } else {
                    $result[$key] = $sanitizedValue;
                }
            }
        }
        return $result;
    }
    
    if (is_object($data)) {
        $result = new \stdClass();
        foreach ($data as $key => $value) {
            $result->$key = sanitizeForJson($value);
        }
        return $result;
    }
    
    if (is_string($data)) {
        // Remove invalid UTF-8 sequences
        $data = mb_convert_encoding($data, 'UTF-8', 'UTF-8');
        // Remove control characters except newline, carriage return, tab
        $data = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/', '', $data);
        return $data;
    }
    
    return $data;
}

/**
 * Send an error response
 * 
 * @param int    $code    HTTP error code
 * @param string $message Error message
 * @param array  $extra   Additional data to include
 * 
 * @return void
 */
function sendErrorResponse($code, $message, $extra = [])
{
    $response = [
        'success' => false,
        'error'   => array_merge([
            'code'    => $code,
            'message' => $message,
        ], $extra),
    ];
    
    sendJsonResponse($response, $code);
}

/**
 * Get the real client IP address
 * 
 * Supports various proxy headers including Cloudflare.
 * 
 * @return string
 */
function getClientIp()
{
    $headers = [
        'HTTP_CF_CONNECTING_IP',     // Cloudflare
        'HTTP_X_FORWARDED_FOR',      // Generic proxies
        'HTTP_X_REAL_IP',            // Nginx proxy
        'HTTP_CLIENT_IP',            // Other proxies
        'REMOTE_ADDR',               // Direct connection
    ];
    
    foreach ($headers as $header) {
        if (!empty($_SERVER[$header])) {
            $ip = $_SERVER[$header];
            
            // X-Forwarded-For may contain multiple IPs, take the first one
            if (strpos($ip, ',') !== false) {
                $ips = explode(',', $ip);
                $ip = trim($ips[0]);
            }
            
            // Validate it's a valid IP address
            if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE)) {
                return $ip;
            }
            
            // Accept private IPs for local development
            if (filter_var($ip, FILTER_VALIDATE_IP)) {
                return $ip;
            }
        }
    }
    
    return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '0.0.0.0';
}

/**
 * Get addon configuration setting value
 * 
 * @param string $setting Setting name
 * 
 * @return string|null
 */
function getAddonSetting($setting)
{
    try {
        $result = Capsule::table('tbladdonmodules')
            ->where('module', 'mrrlytics')
            ->where('setting', $setting)
            ->value('value');
        
        return $result;
    } catch (\Exception $e) {
        return null;
    }
}

/**
 * Check rate limit for the current IP
 * 
 * Uses a sliding window algorithm with 1-minute windows.
 * 
 * @param string $ip          Client IP address
 * @param int    $maxRequests Maximum requests per minute
 * 
 * @return array ['allowed' => bool, 'remaining' => int, 'retry_after' => int]
 */
function checkRateLimit($ip, $maxRequests)
{
    $currentTime = time();
    $windowStart = $currentTime - 60; // 1-minute window
    
    try {
        // Clean up old records (older than 2 minutes)
        Capsule::table('mod_mrrlytics_ratelimit')
            ->where('request_time', '<', $currentTime - 120)
            ->delete();
        
        // Count requests in the current window
        $requestCount = Capsule::table('mod_mrrlytics_ratelimit')
            ->where('ip_address', $ip)
            ->where('request_time', '>=', $windowStart)
            ->count();
        
        if ($requestCount >= $maxRequests) {
            // Get the timestamp of the oldest request in the window
            $oldestRequest = Capsule::table('mod_mrrlytics_ratelimit')
                ->where('ip_address', $ip)
                ->where('request_time', '>=', $windowStart)
                ->orderBy('request_time', 'asc')
                ->value('request_time');
            
            $retryAfter = $oldestRequest ? ($oldestRequest + 60 - $currentTime) : 60;
            
            return [
                'allowed'     => false,
                'remaining'   => 0,
                'retry_after' => max(1, $retryAfter),
            ];
        }
        
        // Record this request
        Capsule::table('mod_mrrlytics_ratelimit')->insert([
            'ip_address'   => $ip,
            'request_time' => $currentTime,
        ]);
        
        return [
            'allowed'     => true,
            'remaining'   => $maxRequests - $requestCount - 1,
            'retry_after' => 0,
        ];
    } catch (\Exception $e) {
        // On error, allow the request (fail open)
        return [
            'allowed'     => true,
            'remaining'   => $maxRequests,
            'retry_after' => 0,
        ];
    }
}

/**
 * Extract the authentication header
 * 
 * Supports both Apache (getallheaders) and CGI/FastCGI (HTTP_ prefix).
 * 
 * @return string|null
 */
function getAuthHeader()
{
    $headers = [];
    
    // Apache and some other servers
    if (function_exists('getallheaders')) {
        $headers = getallheaders();
        if ($headers === false) {
            $headers = [];
        }
    }
    
    // Normalize keys to lowercase
    $headers = array_change_key_case($headers, CASE_LOWER);
    
    if (isset($headers['x-mrrlytics-key'])) {
        return $headers['x-mrrlytics-key'];
    }
    
    // Fallback for servers using HTTP_ prefix
    if (isset($_SERVER['HTTP_X_MRRLYTICS_KEY'])) {
        return $_SERVER['HTTP_X_MRRLYTICS_KEY'];
    }
    
    return null;
}

// ============================================================================
// MAIN EXECUTION FLOW
// ============================================================================

try {
    // 1. Verify HTTP method
    $requestMethod = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : 'GET';
    if ($requestMethod !== 'GET') {
        sendErrorResponse(405, 'Method not allowed. Use GET.');
    }
    
    // 2. Get and validate API Key
    $providedKey = getAuthHeader();
    
    if (empty($providedKey)) {
        sendErrorResponse(401, 'Missing API key. Include X-MRRlytics-Key header.');
    }
    
    $storedKey = getAddonSetting('API_KEY');
    
    if (empty($storedKey)) {
        sendErrorResponse(500, 'API key not configured in WHMCS addon settings.');
    }
    
    // Constant-time comparison to prevent timing attacks
    if (!hash_equals($storedKey, $providedKey)) {
        sendErrorResponse(401, 'Invalid API key.');
    }
    
    // 3. Check rate limit
    $clientIp = getClientIp();
    $rateLimitSetting = getAddonSetting('RATE_LIMIT');
    $rateLimit = $rateLimitSetting ? (int) $rateLimitSetting : 300;
    $rateLimitResult = checkRateLimit($clientIp, $rateLimit);
    
    // Add rate limit headers
    header('X-RateLimit-Limit: ' . $rateLimit);
    header('X-RateLimit-Remaining: ' . $rateLimitResult['remaining']);
    
    if (!$rateLimitResult['allowed']) {
        header('Retry-After: ' . $rateLimitResult['retry_after']);
        sendErrorResponse(429, 'Rate limit exceeded. Try again later.', [
            'retry_after' => $rateLimitResult['retry_after'],
        ]);
    }
    
    // 4. Parse query parameters
    $limit = isset($_GET['limit']) ? (int) $_GET['limit'] : 1000;
    $offset = isset($_GET['offset']) ? (int) $_GET['offset'] : 0;
    $since = isset($_GET['since']) ? $_GET['since'] : null;
    
    // Validate limit (max 5000)
    $limit = max(1, min(5000, $limit));
    $offset = max(0, $offset);
    
    // Validate 'since' date format
    if ($since !== null) {
        $sinceTimestamp = strtotime($since);
        if ($sinceTimestamp === false) {
            sendErrorResponse(400, 'Invalid "since" parameter. Use ISO8601 format (e.g., 2024-01-01T00:00:00Z).');
        }
        $since = date('Y-m-d H:i:s', $sinceTimestamp);
    }
    
    // 5. Load and execute the data extractor
    require_once __DIR__ . '/lib/DataExtractor.php';
    
    $extractor = new \MRRlytics\DataExtractor($limit, $offset, $since, $debugMode);
    $result = $extractor->extract();
    
    // 6. Send successful response
    sendJsonResponse($result, 200);
    
} catch (\Exception $e) {
    // Handle any uncaught exceptions
    $extra = [];
    if ($debugMode) {
        $extra['file'] = $e->getFile();
        $extra['line'] = $e->getLine();
        $extra['trace'] = explode("\n", $e->getTraceAsString());
    }
    sendErrorResponse(500, 'Internal server error: ' . $e->getMessage(), $extra);
}
